const axios = require("axios");

/**
 * Sends a prompt to the Google Gemini AI model using the HTTP REST API.
 * This utilizes the 'gemini-2.5-flash' model for fast and cost-effective text generation.
 * 
 * @param {string} prompt - The question or task for the AI.
 * @param {string} systemInstruction - Optional instructions to set the persona or constraints for the AI.
 * @returns {Promise<string>} The generated text response from the AI.
 */
const generateAIResponse = async (prompt, systemInstruction = "") => {
    try {
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            console.warn("WARNING: GEMINI_API_KEY is not defined in the environment variables.");
            return "AI service is currently unavailable (API key missing).";
        }

        // Using Gemini 2.5 Flash API endpoint
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
        
        // Construct the request body matching Gemini's REST API payload format
        const requestBody = {
            contents: [
                {
                    parts: [
                        {
                            text: prompt
                        }
                    ]
                }
            ]
        };

        // Inject system instructions if specified (useful for setting tutor persona)
        if (systemInstruction) {
            requestBody.systemInstruction = {
                parts: [
                    {
                        text: systemInstruction
                    }
                ]
            };
        }

        const response = await axios.post(url, requestBody, {
            headers: {
                "Content-Type": "application/json"
            }
        });

        // Safely extract the generated text from response candidate structure
        const candidates = response.data?.candidates;
        if (candidates && candidates.length > 0) {
            const textResponse = candidates[0].content?.parts[0]?.text;
            return textResponse;
        }

        return "No response generated by the AI.";
    } catch (error) {
        console.error("AI Helper Error:", error.response?.data || error.message);
        throw new Error("AI Generation failed: " + (error.response?.data?.error?.message || error.message));
    }
};

module.exports = { generateAIResponse };
